application:
  method:
    git:
      enabled: true
      exception: false
    composer:
      enabled: true
      exception: false
  analyzer:
    parallel-lint:
      enabled: true
      exception: true
    php-cs-fixer:
      enabled: true
      exception: false
    phpcbf:
      enabled: true
      exception: false
    phpcs:
      enabled: true
      exception: false
    phpmd:
      enabled: true
      exception: false
    phploc:
      enabled: true
      exception: false
    phpcpd:
      enabled: true
      exception: false
    phpdcd:
      enabled: true
      exception: false
    phpunit:
      enabled: true
      exception: true
